// lib/countries.ts
// Lista de países (nomes em português) para campos de nacionalidade/país.
// Angola surge destacada no topo por ser o país de operação da organização;
// as restantes seguem em ordem alfabética.

export interface CountryOption {
  value: string;
  label: string;
}

const REST_OF_WORLD: string[] = [
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Antígua e Barbuda',
  'Arábia Saudita',
  'Argélia',
  'Argentina',
  'Arménia',
  'Austrália',
  'Áustria',
  'Azerbaijão',
  'Bahamas',
  'Bangladeche',
  'Barbados',
  'Barém',
  'Bélgica',
  'Belize',
  'Benim',
  'Bielorrússia',
  'Bolívia',
  'Bósnia e Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunei',
  'Bulgária',
  'Burquina Faso',
  'Burundi',
  'Butão',
  'Cabo Verde',
  'Camarões',
  'Camboja',
  'Canadá',
  'Catar',
  'Cazaquistão',
  'Chade',
  'Chile',
  'China',
  'Chipre',
  'Colômbia',
  'Comores',
  'Congo-Brazzaville',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa do Marfim',
  'Costa Rica',
  'Croácia',
  'Cuba',
  'Dinamarca',
  'Domínica',
  'Egito',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eritreia',
  'Eslováquia',
  'Eslovénia',
  'Espanha',
  'Estados Unidos da América',
  'Estónia',
  'Essuatíni',
  'Etiópia',
  'Fiji',
  'Filipinas',
  'Finlândia',
  'França',
  'Gabão',
  'Gâmbia',
  'Gana',
  'Geórgia',
  'Granada',
  'Grécia',
  'Guatemala',
  'Guiana',
  'Guiné',
  'Guiné Equatorial',
  'Guiné-Bissau',
  'Haiti',
  'Honduras',
  'Hungria',
  'Iémen',
  'Índia',
  'Indonésia',
  'Irão',
  'Iraque',
  'Irlanda',
  'Islândia',
  'Israel',
  'Itália',
  'Jamaica',
  'Japão',
  'Jibuti',
  'Jordânia',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letónia',
  'Líbano',
  'Libéria',
  'Líbia',
  'Listenstaine',
  'Lituânia',
  'Luxemburgo',
  'Macedónia do Norte',
  'Madagáscar',
  'Malásia',
  'Malawi',
  'Maldivas',
  'Mali',
  'Malta',
  'Marrocos',
  'Maurícia',
  'Mauritânia',
  'México',
  'Mianmar',
  'Micronésia',
  'Moçambique',
  'Moldávia',
  'Mónaco',
  'Mongólia',
  'Montenegro',
  'Namíbia',
  'Nauru',
  'Nepal',
  'Nicarágua',
  'Níger',
  'Nigéria',
  'Noruega',
  'Nova Zelândia',
  'Omã',
  'Países Baixos',
  'Palau',
  'Panamá',
  'Papua-Nova Guiné',
  'Paquistão',
  'Paraguai',
  'Peru',
  'Polónia',
  'Portugal',
  'Quénia',
  'Quirguistão',
  'Reino Unido',
  'República Centro-Africana',
  'República Checa',
  'República Democrática do Congo',
  'República Dominicana',
  'Ruanda',
  'Roménia',
  'Rússia',
  'Salomão',
  'Samoa',
  'Santa Lúcia',
  'São Cristóvão e Neves',
  'San Marino',
  'São Tomé e Príncipe',
  'São Vicente e Granadinas',
  'Senegal',
  'Serra Leoa',
  'Sérvia',
  'Seicheles',
  'Singapura',
  'Síria',
  'Somália',
  'Sri Lanca',
  'Sudão',
  'Sudão do Sul',
  'Suécia',
  'Suíça',
  'Suriname',
  'Tailândia',
  'Taiwan',
  'Tajiquistão',
  'Tanzânia',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trindade e Tobago',
  'Tunísia',
  'Turquemenistão',
  'Turquia',
  'Tuvalu',
  'Ucrânia',
  'Uganda',
  'Uruguai',
  'Usbequistão',
  'Vanuatu',
  'Vaticano',
  'Venezuela',
  'Vietname',
  'Zâmbia',
  'Zimbabué',
].sort((a, b) => a.localeCompare(b, 'pt'));

export const COUNTRIES: CountryOption[] = [
  { value: 'Angola', label: 'Angola' },
  ...REST_OF_WORLD.map((name) => ({ value: name, label: name })),
];
